INSERT INTO ACCOUNT (ID, CURRENTBALANCE)
VALUES
    (nextval('HIBERNATE_SEQUENCE'), 2000),
    (nextval('HIBERNATE_SEQUENCE'), 0)
;

INSERT INTO TRANSACTION (ID, AMOUNT, DATE, METHOD, STATUS, SOURCEACCOUNT_ID, DESTINATIONACCOUNT_ID)
VALUES
    (nextval('HIBERNATE_SEQUENCE'), 1500, parsedatetime('29-06-1991 03:30:00', 'dd-MM-yyyy hh:mm:ss'), 'BANK_TRANSFER', 'COMPLETED', 2, 1),
    (nextval('HIBERNATE_SEQUENCE'), 500, parsedatetime('22-05-2018 17:43:00', 'dd-MM-yyyy hh:mm:ss'), 'BANK_TRANSFER', 'COMPLETED', 2, 1)
;

