INSERT INTO ACCOUNT (ID)
VALUES
    (nextval('HIBERNATE_SEQUENCE')),
    (nextval('HIBERNATE_SEQUENCE'))
;

INSERT INTO TRANSACTION (ID, AMOUNT, DATE, METHOD, STATUS, SOURCEACCOUNT_ID, DESTINATIONACCOUNT_ID)
VALUES
    (nextval('HIBERNATE_SEQUENCE'), 1500, parsedatetime('29-06-1991 03:30:00', 'dd-MM-yyyy hh:mm:ss'), 'BANK_TRANSFER', 'COMPLETED', 2, 1),
    (nextval('HIBERNATE_SEQUENCE'), 500, parsedatetime('22-05-2018 17:43:00', 'dd-MM-yyyy hh:mm:ss'), 'BANK_TRANSFER', 'COMPLETED', 2, 1)
;

INSERT INTO MOVEMENT (ID, ACCOUNT_ID, AMOUNT)
VALUES
    (nextval('HIBERNATE_SEQUENCE'), 1, -1500),
    (nextval('HIBERNATE_SEQUENCE'), 2, 1500),
    (nextval('HIBERNATE_SEQUENCE'), 1, -500),
    (nextval('HIBERNATE_SEQUENCE'), 2, 500)
;

INSERT INTO TRANSACTION_MOVEMENT (TRANSACTION_ID, MOVEMENTS_ID)
VALUES
    (3,5),
    (3,6),
    (4,7),
    (4,8)
;

INSERT INTO ACCOUNT_MOVEMENT (ACCOUNT_ID, MOVEMENTS_ID)
VALUES
    (1,5),
    (2,6),
    (1,7),
    (2,8)
;